sudo: required

addons:
    artifacts: true

services:
    - docker

before_install:
    - docker pull shadowsocks/android-ndk-go
    - chmod -R a+wrx .

script:
    - docker run --rm -v ${PWD}:/build shadowsocks/android-ndk-go bash -c "cd /build; ./gradlew assembleDebug check"
