sudo: required

addons:
    artifacts: true

services:
    - docker

before_install:
    - docker pull circleci/android:api-28
    - chmod -R a+wrx .

script:
    - docker run --rm -v ${PWD}:/build circleci/android:api-28 bash -c "cd /build; ./gradlew assembleDebug check"
