language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-21.1.1
  - android-21
  - extra-google-m2repository
  - extra-android-m2repository
cache:
- apt
before_install:
- echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
- sudo apt-get update
install:
- sudo apt-get install -y sbt libc6-dev-i386 lib32ncurses5-dev libx11-dev g++-multilib lib32z1-dev ccache
- export NDK_CCACHE=ccache
- export ARCH=`uname -m`
- wget http://dl.google.com/android/ndk/android-ndk-r10d-linux-${ARCH}.bin
- chmod +x android-ndk-r10d-linux-${ARCH}.bin
- ./android-ndk-r10d-linux-${ARCH}.bin -y | grep gcc
- export ANDROID_NDK_HOME=`pwd`/android-ndk-r10d
- export PATH=${PATH}:${ANDROID_NDK_HOME}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
script:
- cp local.properties.travis local.properties
- ./build.sh
- sbt android:package-release
- exit 0
