language: android

jdk:
  - oraclejdk8

env:
    global:
        - NDK_VERSION=r16
        - NDK_CCACHE=ccache
        - GOROOT_BOOTSTRAP=$GOROOT
        - ANDROID_NDK_HOME=$HOME/.android/android-ndk-${NDK_VERSION}
        - PATH=${ANDROID_NDK_HOME}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${PATH}

cache:
    directories:
        - $HOME/.gradle

android:
    components:
        - tools
        - android-27
        - build-tools-27.0.2

install:
    - >
      if [ ! -d "$ANDROID_NDK_HOME" ]; then
          mkdir -p $ANDROID_NDK_HOME;
          pushd $HOME/.android;
          export ARCH=`uname -m`;
          wget -q http://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-linux-${ARCH}.zip;
          unzip -q android-ndk-${NDK_VERSION}-linux-${ARCH}.zip;
          popd;
      fi
    - >

script:
    - ./gradlew assembleDebug
