language: scala
jdk:
- oraclejdk7
scala:
- 2.9.2
before_install:
- sudo apt-get update
- sudo apt-get install libc6-dev-i386
- sudo apt-get install lib32ncurses5-dev
- sudo apt-get install libx11-dev
- sudo apt-get install g++-multilib
- sudo apt-get install lib32z1-dev
- export ARCH=`uname -m`
- wget http://dl.google.com/android/android-sdk_r21-linux.tgz
- tar xf android-sdk_r21-linux.tgz
- wget http://dl.google.com/android/ndk/android-ndk-r8e-linux-${ARCH}.tar.bz2
- tar xf android-ndk-r8e-linux-${ARCH}.tar.bz2
- export ANDROID_NDK_HOME=`pwd`/android-ndk-r8e
- export ANDROID_HOME=`pwd`/android-sdk-linux
- export PATH=${PATH}:${ANDROID_NDK_HOME}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
- android update sdk --filter tools,platform-tools,android-16 --no-ui --no-https -a
install:
- gem install travis-artifacts
before_script:
- export JAVA_OPTS=-Xmx2048m
script:
- ./build-ndk.sh
- rm -rf ${ANDROID_NDK_HOME}
- wget https://raw.github.com/paulp/sbt-extras/master/sbt
- chmod u+x ./sbt
- cp local.sbt.example local.sbt
- ./sbt clean android:package-debug
after_success:
- ./sbt deploy
env:
  global:
  - "ARTIFACTS_AWS_REGION=ap-northeast-1"
  - "ARTIFACTS_S3_BUCKET=travis-ci"
  - secure: "GkAdnMh07id2VKhpCW16lE73A0LK2Jsk3hzkFvdx76JKW8FjLgaimLJ2T/+i\nxFfDw8XBinLE09dqg8JxSNS6JbLHLcav8P3yJIlzFh1NqfJABU9U4I8atb6P\nITSdSo9nb3LX6sB8SOU0nqXb5U+nj7jiekQqiBhmEmu6iDmMtfU="
  - secure: "eCh5BjCFccp+sB/FIrjsmxJU4475D4qiWvDV++khcIHLel6lgUjDX18ImBlJ\n+IdiCKxvR6EpRDV1Cs4gJ2jZEAV0PbojQMoQOXbs1FLggM8RRq/Re1qWQFq7\nWkBRjjr8w8ddjJZHRo459cTUvgvD7krhp07coabAnEahDaGWSUo="
