language: android

jdk:
  - oraclejdk8

env:
    global:
        - GOROOT_BOOTSTRAP=$GOROOT

cache:
    directories:
        - $HOME/.gradle

install:
    - pushd $ANDROID_HOME
    - rm -rf tools
    - wget -q https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -O tools.zip
    - unzip -q tools.zip
    - popd
    - touch $HOME/.android/repositories.cfg
    - yes | sdkmanager
        "build-tools;27.0.2"
        ndk-bundle
        "platforms;android-27"
      >/dev/null

script:
    - ./gradlew assembleDebug
