version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: shadowsocks/shadowsocks-android:circleci
    environment:
      JVM_OPTS: -Xmx5g
    resource_class: medium+
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}
      - restore_cache:
          key: go-full-{{ checksum "~/code/.git/modules/core/src/overture/go/HEAD" }}
      - run:
          name: Run Build and Tests
          command: ./gradlew assembleDebug check
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.android/build-cache
          key: jars-{{ checksum "build.gradle" }}
      - save_cache:
          paths:
            - ~/code/core/src/overture/go
          key: go-full-{{ checksum "~/code/.git/modules/core/src/overture/go/HEAD" }}
      - store_artifacts:
          path: mobile/build/outputs/apk
          destination: apk/mobile
      - store_artifacts:
          path: tv/build/outputs/apk
          destination: apk/tv
      - store_artifacts:
          path: core/build/reports
          destination: reports/core
      - store_artifacts:
          path: mobile/build/reports
          destination: reports/mobile
      - store_artifacts:
          path: plugin/build/reports
          destination: reports/plugin
      - store_artifacts:
          path: tv/build/reports
          destination: reports/tv
